Add RBAC rules and basic service account
artefactual-sdps/enduro pull request #721
Opened 2023-09-23 21:41 UTC by sbreker

Adds a named service account and restricts access to retrieving pod info only.

2023-09-28 09:05 UTC, scollazo commented
I'm getting an error when applying this:

 ```error: error validating "serviceaccount.yaml": error validating data: ValidationError(ServiceAccount.metadata): unknown field "automountServiceAccountToken" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta; if you choose to ignore these errors, turn validation off with --validate=false```

I'm using :
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6+k3s1", GitCommit:"a8e0c66d1a90a2bbc4ffa975129ca35756cc7c14", GitTreeState:"clean", BuildDate:"2022-09-28T16:52:07Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6+k3s1", GitCommit:"a8e0c66d1a90a2bbc4ffa975129ca35756cc7c14", GitTreeState:"clean", BuildDate:"2022-09-28T16:52:07Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```

2023-09-28 09:13 UTC, scollazo requested changes

2023-09-28 09:13 UTC, scollazo commented on hack/kube/base/serviceaccount.yaml
> +  automountServiceAccountToken: false
This should be at metadata level, as per https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#opt-out-of-api-credential-automounting

2023-09-29 15:20 UTC, sbreker commented on hack/kube/base/serviceaccount.yaml
> +  automountServiceAccountToken: false
This is fixed.

2023-10-03 16:56 UTC, scollazo approved these changes
LGTM

2023-10-03 17:11 UTC, merged