Build binaries from build_dist.sh
artefactual-sdps/enduro pull request #747
Opened 2023-11-01 10:27 UTC by scollazo

2023-11-08 19:20 UTC, djjuhasz requested changes
@scollazo I don't understand the purpose of this change, and the tests are not passing.  Is it still necessary?

2023-11-10 11:22 UTC, sevein requested changes
A detailed description would be nice. I'm guessing that you want to have the following syntax:

    ./hack/build_dist.sh enduro-a3m-worker

Instead of:

    ./hack/build_dist.sh -o enduro-a3m-worker ./cmd/enduro-a3m-worker

For me the main issue with this change is that I won't be able to pass arbitrary flags to `go build`, e.g. something I've been doing recently:

    ./hack/build_dist.sh -cover -o /tmp/test-instrumented-binary ./cmd/enduro-a3m-worker

2023-11-10 11:22 UTC, sevein commented on hack/build_dist.sh
> + esac
There is a whitespace before `esac`, is that on purpose?

2023-11-10 11:22 UTC, sevein commented on hack/build_dist.sh
> +        TARGETPATH=.
Mixed use of tabs and whitespaces for indenting.

2023-11-15 11:09 UTC, scollazo commented
> ./hack/build_dist.sh -o enduro-a3m-worker ./cmd/enduro-a3m-worker

That's all I need, closing this

2023-11-15 11:09 UTC, closed without merging