Save AM job data in poll transfer activity
artefactual-sdps/enduro pull request #803
Opened 2023-12-05 21:34 UTC by djjuhasz

Related issue #783.

- Create an `am.Jobs` package to query the AM jobs endpoint, and save the data to the package service as preservation tasks
- Integrate `am.Jobs` into PollTransferActivity
- Set the preservation task `startedAt` and `completedAt` to the current time when saving the data to the database becuase the Enduro dashboard won't show tasks that don't have a `startedAt` time

2023-12-06 18:21 UTC, sevein approved these changes
Nicely done!

2023-12-06 18:21 UTC, sevein commented on internal/am/jobs.go
> +type PreservationAction struct {
Delving into naming conventions once more! What do you think about renaming PreservationAction to JobTracker? This name might better reflect its role in maintaining a stateful tracking of jobs.

2023-12-06 18:21 UTC, sevein commented on internal/am/jobs.go
> +// SaveTasks polls the Archivematica jobs list endpoint to get a list of
s/polls/fetches?

2023-12-06 18:21 UTC, sevein commented on internal/am/jobs.go
> +	savedIDs map[string]struct{}
This is perfect, but now wondering whether we should eventually adopt some kind of generic data structure, e.g. https://github.com/zyedidia/generic has a set type - see https://go.dev/play/p/hHNbIN2msXf. `struct{}{}` is a memory trick that may be as well hidden I guess.

2023-12-06 18:21 UTC, sevein commented on internal/am/jobs.go
> +		pt.CompletedAt = sql.NullTime{Time: pa.clock.Now(), Valid: true}
We should probably call pa.clock.Now() just once.

2023-12-06 18:23 UTC, sevein commented on internal/am/poll_transfer.go
> +				count, err := pa.SaveTasks(ctx, params.TransferID)
Should we use the context with timeout previously defined to save the tasks? I'm thinking if things go wrong here we could be missing a heartbeat, but I don't know if that's a big deal.

2023-12-06 18:52 UTC, djjuhasz commented on internal/am/jobs.go
> +// SaveTasks polls the Archivematica jobs list endpoint to get a list of
I did s/polls/queries

2023-12-06 19:39 UTC, sevein commented on internal/am/jobs.go
> +	savedIDs map[string]struct{}
I meant in the long term really, not asking you to do it now.

2023-12-06 21:00 UTC, Diogenesoftoronto requested changes
Looks good so far.

2023-12-06 21:00 UTC, Diogenesoftoronto commented on internal/am/jobs_test.go
> +func TestPreservationAction_UpdateTasks(t *testing.T) {
We can have t.Parrellel here as well

2023-12-06 21:00 UTC, Diogenesoftoronto commented on internal/am/poll_transfer.go
> +				count, err := pa.SaveTasks(ctx, params.TransferID)
Considering that heartbeats are half the configurable time? seems like it could be. if someone decided polling once an hour or something crazy. Maybe just a note for setup that increasing polling time by a large amount may result in missing polling intervals for tasks that are saved.

2023-12-06 21:00 UTC, Diogenesoftoronto commented on internal/am/poll_transfer_test.go
>  func TestPollTransferActivity(t *testing.T) {
we can use t.Parallel here

2023-12-06 22:15 UTC, djjuhasz commented on internal/am/poll_transfer.go
> +				count, err := pa.SaveTasks(ctx, params.TransferID)
I've updated this method call to use `reqCtx` but I refactored the code so I didn't have to pass the context cancel function to the `SaveTasks()` method too.  I've also increased the context timeout to the full `PollInterval`, because the Heartbeat Timeout is set to `2 * PollInterval` so we should be well under that deadline.

2023-12-06 22:57 UTC, Diogenesoftoronto approved these changes

2023-12-06 23:12 UTC, merged

2023-12-07 06:19 UTC, sevein commented on internal/am/poll_transfer.go
> +				count, err := pa.SaveTasks(ctx, params.TransferID)
Good call, the simplified loop is much easier to read now.