Centralize Archivematica documentation
artefactual-sdps/enduro pull request #828
Opened 2024-01-12 17:30 UTC by Diogenesoftoronto

- All changes required to get archivematica are available in one place.
- A checklist has been added to help guide users further for the correct
setup.
- Bi-directional linking has been applied to the tilt environment config.

2024-01-12 17:58 UTC, djjuhasz commented on docs/src/dev-manual/archivematica.md
> +    The secret generator is used via tilt so users CANNOT manually apply
The secret generator is used via ~~t~~Tilt so users CANNOT manually apply

2024-01-12 18:09 UTC, djjuhasz requested changes
I like the checklist! :+1: I'm curious to see how it renders in readthedocs. 

I noted a few minor formatting errors and typos.

2024-01-12 18:09 UTC, djjuhasz commented on docs/src/dev-manual/archivematica.md
> +    the Kubernetes commands for these operations. Understanding the way that
the Kubernetes commands for these operations. Understanding the way ~~that~~these

2024-01-12 18:09 UTC, djjuhasz commented on docs/src/dev-manual/archivematica.md
> +    - **Contents to Check:**
Looks like the indenting is wrong here.

2024-01-12 18:09 UTC, djjuhasz commented on docs/src/dev-manual/archivematica.md
> +			`http://host.k3d.internal:62080`) - User credentials
Missing newlines?

2024-01-12 18:09 UTC, djjuhasz commented on docs/src/dev-manual/archivematica.md
> +There is more information on the configuration of the [Tilt Environment].
Blank line before this one?

2024-01-12 21:32 UTC, djjuhasz approved these changes
LGTM :+1:

2024-01-13 00:56 UTC, merged

2024-01-19 08:58 UTC, sevein commented
> I like the checklist! 👍 I'm curious to see how it renders in readthedocs.

It doesn't look great:
(FYI: readthedocs provides a preview link in the status checks: https://enduro--828.org.readthedocs.build/)

![image](https://github.com/artefactual-sdps/enduro/assets/606459/29f4c0c6-3a93-4b7a-900d-8a761c66910c)