Update go in devbox
artefactual-sdps/enduro pull request #890
Opened 2024-03-14 16:17 UTC by Diogenesoftoronto

2024-03-14 17:16 UTC, sevein commented on devbox.json
> +    "go_1_22@latest"
Do we have to keep go_1_21?

2024-03-14 17:18 UTC, sevein commented on devbox.json
> +    "go_1_22@latest"
Have you noticed that it's installing 1.22.0 instead of 1.22.1? Can that be changed?

2024-03-15 05:53 UTC, Diogenesoftoronto commented on devbox.json
> +    "go_1_22@latest"
Oh absolutely. Seems that stuck around during some work I was doing in the repo.

2024-03-21 16:19 UTC, sevein commented on devbox.lock
> +          "store_path": "/nix/store/88y9r33p3j8f7bc8sqiy9jdlk7yqfrlg-go-1.22.0"
Do you know why it chooses to install 1.22.0 instead of 1.22.1?

2024-03-25 15:24 UTC, Diogenesoftoronto commented on devbox.lock
> +          "store_path": "/nix/store/88y9r33p3j8f7bc8sqiy9jdlk7yqfrlg-go-1.22.0"
huh must have been before the nix package repo had been updated, when i load the latest it works with 1.22.1 now

2024-03-26 09:03 UTC, sevein requested changes
Weird, I still see "1.22.0".

2024-04-02 16:24 UTC, Diogenesoftoronto commented
> Weird, I still see "1.22.0".

Oh my gosh, sorry for the long update, some of my work got lost. I am learning to use gitbutler and some of my changes were not recovered because of the way that it works.

2024-04-03 20:49 UTC, sevein approved these changes

2024-04-03 21:27 UTC, merged